matikgp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pokemoni/', include('pokemoni.urls')),
]

pokemoni/urls.py
from django.urls import path

from . import views

app_name = 'pokemoni'

urlpatterns = [
    path('trening', views.trening, name='trening'),
    path('obchod', views.obchod, name='obchod'),
    path('prehlad', views.prehlad, name='prehlad'),
    path('druzinka/<int:num>', views.druzinka, name='druzinka'),
    path('jedalen', views.jedalen, name='jedalen'),
    path('spravca', views.spravca, name='spravca'),
    path('', views.zoznam, name='index'),
]

pokemoni/models.py
from django.db import models

class Druzinka(models.Model):
    nazov = models.CharField(max_length=100, unique=True)
    url_number = models.IntegerField(unique=True, null=True)

    def __str__(self):
        return "Družinka {}".format(self.nazov)

class Ucet(models.Model):
    idDruzinka = models.OneToOneField(Druzinka, on_delete=models.CASCADE, null=True)

    peniaze = models.IntegerField(default=1000)
    popularita = models.IntegerField(default=0)

    def __str__(self):
        return "Účet družinky {}".format(self.idDruzinka.nazov)

class Pokemon(models.Model):
    nazov = models.CharField(max_length=100)
    idDruzinka = models.ForeignKey(Druzinka, on_delete=models.CASCADE)

    sila = models.IntegerField(default=0)
    rychlost = models.IntegerField(default=0)
    postreh = models.IntegerField(default=0)
    odolnost = models.IntegerField(default=0)

    energia = models.IntegerField(default=10)
    jedol = models.BooleanField(default=False)

    def __str__(self):
        return "Pokémon {} družinky {}".format(self.nazov, self.idDruzinka.nazov)

class Trener(models.Model):
    meno = models.CharField(max_length=100)
    cena = models.IntegerField(default=0)
    vMeste = models.BooleanField(default=False)

    qSila = models.IntegerField(default=0)
    qRychlost = models.IntegerField(default=0)
    qPostreh = models.IntegerField(default=0)
    qOdolnost = models.IntegerField(default=0)

    def __str__(self):
        return "Tréner {}".format(self.meno)

class Kurz(models.Model):
    idTrener = models.ForeignKey(Trener, on_delete=models.CASCADE)
    idPokemon = models.ForeignKey(Pokemon, on_delete=models.CASCADE)

    def __str__(self):
        return "Kurz cislo {}".format(self.id)

class Akcia(models.Model):
    meno = models.CharField(max_length=100)

    def __str__(self):
        return "{}".format(self.meno)

pokemoni/forms.py
from django import forms

from .models import Trener, Druzinka, Akcia

class TreningForm(forms.Form):
    trener_meno = forms.ModelChoiceField(queryset=Trener.objects.filter(vMeste=True), label='Meno trénera')

    pokemon_id = forms.IntegerField(label='ID pokémona')

class ObchodForm(forms.Form):
    nova_druzinka = forms.ModelChoiceField(queryset=Druzinka.objects.all(), label='Nová družinka')

    novy_nazov = forms.CharField(max_length=100, label='Nový názov', required=False)

    pokemon_id = forms.IntegerField(label='ID pokémona')

class JedalenForm(forms.Form):
    pokemon_id = forms.IntegerField(label='ID pokémona')

class SpravcaForm(forms.Form):
    akcia = forms.ModelChoiceField(queryset=Akcia.objects.all(), label='Akcia')

pokemoni/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect

import time
from random import randint, uniform

from .models import Pokemon, Trener, Kurz, Druzinka, Ucet, Akcia
from .forms import TreningForm, ObchodForm, JedalenForm, SpravcaForm

def bezi():
    z = zaciatok()
    k = koniec()
    t = round(time.time())
    if z < t and t < k:
        return True
    else:
        return False

def trening(request):
    template_name = 'pokemoni/trening.html'
    form = TreningForm()
    be = bezi()

    if request.method == 'POST':
        try:
            trener = Trener.objects.get(pk=request.POST['trener_meno'])

        except (KeyError, ValueError, Trener.DoesNotExist):
            return render(request, template_name, {'be': be, 'form': form, 'error_message': 'Tréner neexistuje'})

        try:
            pokemon = Pokemon.objects.get(pk=request.POST['pokemon_id'])

        except (KeyError, ValueError, Pokemon.DoesNotExist):
            return render(request, template_name, {'be': be, 'form': form, 'error_message': 'Pokémon neexistuje'})

        if not hasattr(pokemon.idDruzinka, 'ucet') or pokemon.idDruzinka.ucet.peniaze < trener.cena:
            return render(request, template_name, {'be': be, 'form': form, 'error_message': 'Družinka nemá dosť peňazí'})

        if pokemon.energia < 5:
            return render(request, template_name, {'be': be, 'form': form, 'error_message': 'Pokémon je vyčerpaný'})

        pokemon.sila += trener.qSila
        pokemon.rychlost += trener.qRychlost
        pokemon.postreh += trener.qPostreh
        pokemon.odolnost += trener.qOdolnost

        pokemon.energia += -5
        pokemon.idDruzinka.ucet.peniaze -= trener.cena

        kurz = Kurz(idTrener=trener, idPokemon=pokemon)
        kurz.save()

        pokemon.idDruzinka.ucet.save()
        pokemon.save()

        return HttpResponseRedirect(reverse('pokemoni:trening'))

    else:
        return render(request, template_name, {'be': be, 'form': form})

def obchod(request):
    template_name = 'pokemoni/obchod.html'
    form = ObchodForm()
    be = bezi()

    if request.method == 'POST':
        try:
            druzinka = Druzinka.objects.get(pk=request.POST['nova_druzinka'])

        except (KeyError, ValueError, Druzinka.DoesNotExist):
            return render(request, template_name, {'be': be, 'form': form, 'error_message': 'Družinka neexistuje'})

        try:
            pokemon = Pokemon.objects.get(pk=request.POST['pokemon_id'])

        except (KeyError, ValueError, Pokemon.DoesNotExist):
            return render(request, template_name, {'be': be, 'form': form, 'error_message': 'Pokémon neexistuje'})

        pokemon.idDruzinka = druzinka
        pokemon.nazov = request.POST['novy_nazov'] if request.POST['novy_nazov'] != '' else pokemon.nazov

        pokemon.save()

        return HttpResponseRedirect(reverse('pokemoni:obchod'))

    else:
        return render(request, template_name, {'be': be, 'form': form})

def jedalen(request):
    template_name = 'pokemoni/jedalen.html'
    form = JedalenForm()
    be = bezi()

    if request.method == 'POST':
        try:
            pokemon = Pokemon.objects.get(pk=request.POST['pokemon_id'])

        except (KeyError, ValueError, Pokemon.DoesNotExist):
            return render(request, template_name, {'be': be, 'form': form, 'error_message': 'Pokémon neexistuje'})

        if not hasattr(pokemon.idDruzinka, 'ucet') or pokemon.idDruzinka.ucet.peniaze < 5:
            return render(request, template_name, {'be': be, 'form': form, 'error_message': 'Družinka nemá dosť peňazí'})

        pokemon.jedol = True
        pokemon.idDruzinka.ucet.peniaze -= 5

        pokemon.save()
        pokemon.idDruzinka.ucet.save()

        return HttpResponseRedirect(reverse('pokemoni:jedalen'))

    else:
        return render(request, template_name, {'be': be, 'form': form})

def zaciatok(t = 10**11):
    if t != 10**11:
        global zaciatok_cas
        zaciatok_cas = round(t)
        with open('setup/zaciatok.txt', 'w') as f:
            f.write(str(zaciatok_cas))
    try:
        with open('setup/zaciatok.txt', 'r') as f:
            t = int(f.readline())
    except(ValueError, FileNotFoundError):
        t = 10**11
    return t

def koniec(t = 10**11):
    if t != 10**11:
        global koniec_cas
        koniec_cas = zaciatok()+(((t-zaciatok())//480)+1)*480
        with open('setup/koniec.txt', 'w') as f:
            f.write(str(round(koniec_cas)))
    try:
        with open('setup/koniec.txt', 'r') as f:
            t = int(f.readline())
    except(ValueError, FileNotFoundError):
        t = 10**11
    return t

# alert("Cas vyprsal!");
def timer():
    zaciatok_hry = zaciatok()
    koniec_hry = koniec()
    teraz = round(time.time())
    if zaciatok_hry < teraz:
        if teraz < koniec_hry:
            t = 480 - ((teraz - zaciatok_hry) % 480) # modulo 60 * dlzka kola v minutach
            m = t // 60
            s = t % 60
        else:
            m, s = 0, -1
    else:
        m, s = -1, 0
    return m, s

def spravca(request):
    template_name = 'pokemoni/spravca.html'
    form = SpravcaForm()
    akcie = Akcia.objects.all()
    k = round((time.time() - zaciatok()) // 480) + 1
    mi, se = timer()

    if request.method == 'POST':
        akcia = str(request.POST['akcia'])
        # 1 - Začni hru
        # 2 - Ukonči hru
        # 3 - Vyhodnoť kolo
        if akcia == '1':
            message = 'Hra začala'
            zaciatok(time.time())
            with open('setup/koniec.txt', 'w') as f:
                f.write('')
        elif akcia == '2':
            message = 'Hra skončí po konci tohto kola (akcia sa odvráti jedine premazaním súboru koniec.txt)'
            koniec(time.time())
        elif akcia == '3':
            message = "Kolo %d bolo vyhodnotené" % (k)
            pokemoni = Pokemon.objects.all()

            sutaz = []

            for pokemon in pokemoni:
                if not hasattr(pokemon.idDruzinka, 'ucet'):
                    continue
                elif not pokemon.jedol:
                    pokemon.idDruzinka = Druzinka.objects.get(nazov='Mrtvoly')
                else:
                    sutaz.append((skore(pokemon), pokemon))
                    pokemon.jedol = False
                    pokemon.energia = min(10, pokemon.energia+2)

                pokemon.save()

            sutaz.sort(reverse=True)

            for i in range(len(sutaz)):
                sutaz[i][1].idDruzinka.ucet.popularita += round(100-((i+1)**2)/50)
                sutaz[i][1].idDruzinka.ucet.peniaze += round((100-i)**2/50)

                sutaz[i][1].idDruzinka.ucet.save()

            treneri = Trener.objects.all()

            for trener in treneri:
                if randint(1, 7) == 4:
                    trener.vMeste = True
                else:
                    trener.vMeste = False

                trener.save()

        else:
            message = 'Akcia '+str(akcia)+' sa nevykonala'
            return render(request, template_name, {'mi': mi, 'se': se, 'kolo': k, 'akcie': akcie, 'form': form, 'message': message})

        return render(request, template_name, {'mi': mi, 'se': se, 'kolo': k, 'akcie': akcie, 'form': form, 'message': message})
    else:
        return render(request, template_name, {'mi': mi, 'se': se, 'kolo': k, 'form': form, 'akcie': akcie})

def prehlad(request):
    template_name = 'pokemoni/prehlad.html'
    ucty = Ucet.objects.all().order_by('-popularita')
    druzinky = Druzinka.objects.all()
    treneri = Trener.objects.filter(vMeste=True)
    return render(request, template_name, {'ucty': ucty, 'druzinky': druzinky, 'treneri': treneri})

def druzinka(request, num):
    template_name = 'pokemoni/druzinka.html'
    druz = Druzinka.objects.get(url_number=num)
    pokemoni = Pokemon.objects.filter(idDruzinka=druz.id)
    ucet = Ucet.objects.get(idDruzinka=druz.id)
    mi, se = timer()
    return render(request, template_name, {'m': mi, 's': se, 'druz': druz, 'pokemoni': pokemoni, 'ucet': ucet})

def zoznam(request):
    template_name = 'pokemoni/zoznam.html'
    druzinky = Druzinka.objects.all()
    return render(request, template_name, {'druzinky': druzinky})

def skore(p):
    return p.sila**3*p.rychlost**4*p.postreh**3.5*p.odolnost**2.5*uniform(0.95, 1.05)

pokemoni/templates/pokemoni/druzinka.html
{% load staticfiles %}

<!-- Auto refresh results -->
<meta http-equiv="refresh" content="5">

<html>
<head>
    <title>{{ druz.nazov }}</title>
     <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/druzinka.css' %}">
	<script>
		var m = {{ m }};
		var s = {{ s }};
		function startTime() {
			if (s<1) {
			  m = m-1;
			  if (m<0) {
				return;
			  };
			  s=60;
			};
			s = s-1;
			m = checkTime(m);
			s = checkTime(s);
			document.getElementById('timer').innerHTML =
			m + ":" + s;
			var t = setTimeout(startTime, 1000);
		}
		function checkTime(i) {
			if (i < 10) {i = "0" + parseInt(i)};  // add zero in front of numbers < 10
			return i;
		}
	</script>
</head>
<body onload="startTime()">
  <div style="width: 100%;">
    <div style="float:left; width: 62%">
        <h1><strong>Čas do konca kola</strong></h1>
		<div id="timer"></div>
    </div>
    <div style="float:right; width: 38%">
        <h1><strong>Stav účtu</strong></h1>
		<div id="u">
			Peniaze: <em>{{ ucet.peniaze }}€</em><br>
			Popularita: <em>{{ ucet.popularita }}</em>
		</div>
    </div>
  </div>
  <div style="clear:both"></div>
  <div>
	  <h1><strong>Pokémoni</strong></h1>
      <table id="t01" class="fixed">
        <col width="50px" />
        <col width="300px" />
        <col width="120px" />
        <col width="120px" />
        <col width="120px" />
        <col width="120px" />
		<col width="120px" />
		<col width="120px" />
        <tr>
          <th>#</th>
        <th>Meno</th>
        <th>Sila</th> 
        <th>Rýchlosť</th>
        <th>Postreh</th>
        <th>Odolnosť</th>
		<th>Energia</th>
		<th>Jedol</th>
        </tr>
        {% for p in pokemoni %}
          <tr>
          <td>.</td>
          <td class="l">{{ p.nazov }}</td>
          <td>{{ p.sila }}</td>
          <td>{{ p.rychlost }}</td>
          <td>{{ p.postreh }}</td>
          <td>{{ p.odolnost }}</td>
		  <td>{{ p.energia }}</td>
		  <td>
			{% if p.jedol %}
				Áno
			{% else %}
				Nie
			{% endif %}
		  </td>
          </tr>
        {% endfor %}
      </table>
  </div>
  <script>
    var x=0;
    x=x+1
    document.getElementById("demo").innerHTML = x;
  </script>
</body>
</html>

pokemoni/templates/pokemoni/jedalen.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Jedáleň</title>
    <link rel="stylesheet" href="{% static 'css/nedostatocne_opravnenia.css' %}">
</head>
<body>
{% if be %}
{% if user.is_authenticated %}
    <h1>Jedáleň</h1>
    {% if error_message %}<strong>{{ error_message }}</strong>{% endif %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Nakŕm" />
    </form>
{% else %}
    <h1 id="no">Na túto stránku nemáte dostatočné oprávnenia!</h1>
    <div id="debug">Pokračujte prihlásením do svojho účtu na <em>host_server_ip</em>/admin/login/?next=/admin/</div>
{% endif %}
{% else %}
<strong>Hra nebeží</strong>
{% endif %}
</body>
</html>

pokemoni/templates/pokemoni/obchod.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Obchod</title>
    <link rel="stylesheet" href="{% static 'css/nedostatocne_opravnenia.css' %}">
</head>
<body>
{% if be %}
{% if user.is_authenticated %}
    <h1>Obchod</h1>
    {% if error_message %}<strong>{{ error_message }}</strong>{% endif %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Kúp pokémona" />
    </form>
{% else %}
    <h1 id="no">Na túto stránku nemáte dostatočné oprávnenia!</h1>
    <div id="debug">Pokračujte prihlásením do svojho účtu na <em>host_server_ip</em>/admin/login/?next=/admin/</div>
{% endif %}
{% else %}
<strong>Hra nebeží</strong>
{% endif %}
</body>
</html>

pokemoni/templates/pokemoni/prehlad.html
{% load staticfiles %}

<!-- Auto refresh results -->
<meta http-equiv="refresh" content="30">

<html>
<head>
    <title>Prehlad</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/prehlad.css' %}">
</head>
<body>
  <div style="width: 100%;">
    <div style="float:left; width: 24%">
      <h1><strong>Popularita</strong></h1>
      {% for ucet in ucty %}
          <div>
            <table id="pop" class="fixed">
              <col width="250px" />
              <col width="50px" />
              <tr>
                <td>{{ ucet.idDruzinka.nazov }}:</td>
                <td class="r"><em>{{ ucet.popularita }}</em></td>
              </tr>
            </table>
          </div>
      {% endfor %}
      </div>
      <div style="float:right; width: 70%">
      <h1><strong>Tréneri v meste</strong></h1>
      <table id="tren">
        <tr>
        <th rowspan="2" id="tren">Meno</th>
        <th rowspan="2" id="tren">Cena</th> 
        <th colspan="4" id="tren">Kvalita trénera</th>
        </tr>
        <tr>
        <th>Sila</th>
        <th>Rýchlosť</th>
        <th>Postreh</th>
        <th>Odolnosť</th>
        </tr>
        {% for trener in treneri %}
          <tr>
          <td class="l">{{ trener.meno }}</td>
          <td>{{ trener.cena }}€</td>
          <td>{{ trener.qSila }}</td>
          <td>{{ trener.qRychlost }}</td>
          <td>{{ trener.qPostreh }}</td>
          <td>{{ trener.qOdolnost }}</td>
          </tr>
        {% endfor %}
      </table>
      </div>
  </div>
  <div style="clear:both"></div>
</body>
</html>

pokemoni/templates/pokemoni/spravca.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Správca</title>
    <link rel="stylesheet" href="{% static 'css/nedostatocne_opravnenia.css' %}">
    <script>
  		var m = {{ mi }};
  		var s = {{ se }};
  		function startTime() {
  			if (s<1) {
  			  m = m-1;
  			  if (m<0) {
  				  alert("Kolo skončilo, vyhodnoť ho!")
  			  };
  			  s=60;
  			};
  			s = s-1;
  			m = checkTime(m);
  			s = checkTime(s);
  			document.getElementById('timer').innerHTML =
  			m + ":" + s;
  			var t = setTimeout(startTime, 1000);
  		}
  		function checkTime(i) {
  			if (i < 10) {i = "0" + parseInt(i)};  // add zero in front of numbers < 10
  			return i;
  		}
  	</script>
</head>
<body onload="startTime()">
    {% if user.is_superuser %}
      <div style="width: 100%;">
        <div style="float:left; width: 40%;">
          <h1>Správca</h1>
          {% if message %}<strong>{{ m }}</strong>{% endif %}
          Prebieha {{ kolo }}. kolo
          <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Vykonaj" />
          </form>
          <h2>Akcie</h2>
          {% for akcia in akcie %}
            <div>{{ akcia.id }} - {{ akcia.meno }}</div>
          {% endfor %}
        </div>
        <div style="float:right; width: 60%;">
          <div>
            <strong><div id="timer"></div></strong>
          </div>
        </div>
      </div>
    {% else %}
        <h1 id="no">Na túto stránku nemáte dostatočné oprávnenia!</h1>
        <div id="debug">Pokračujte prihlásením do svojho účtu na <em>host_server_ip</em>/admin/login/?next=/admin/</div>
    {% endif %}
</body>
</html>

pokemoni/templates/pokemoni/trening.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Tréning</title>
    <link rel="stylesheet" href="{% static 'css/nedostatocne_opravnenia.css' %}">
</head>
<body>
{% if be %}
{% if user.is_authenticated %}
    <h1>Tréning</h1>
    {% if error_message %}<strong>{{ error_message }}</strong>{% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Trénuj" />
    </form>
{% else %}
    <h1 id="no">Na túto stránku nemáte dostatočné oprávnenia!</h1>
    <div id="debug">Pokračujte prihlásením do svojho účtu na <em>host_server_ip</em>/admin/login/?next=/admin/</div>
{% endif %}
{% else %}
<strong>Hra nebeží</strong>
{% endif %}
</body>
</html>

pokemoni/templates/pokemoni/zoznam.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Zoznam podstránok</title>
    <link rel="stylesheet" href="{% static 'css/nedostatocne_opravnenia.css' %}">
</head>
<body>
{% if user.is_authenticated %}
<h1>Zoznam podstránok</h1>
<ul>
    <li><a href="{% url 'admin:index' %}">Admin</a></li>
    <li><a href="{% url 'pokemoni:spravca' %}">Správca hry</a></li>
    <li><a href="{% url 'pokemoni:prehlad' %}">Všeobecný prehľad</a></li>
    <li><a href="{% url 'pokemoni:trening' %}">Tréningové centrum</a></li>
    <li><a href="{% url 'pokemoni:obchod' %}">Obchod s pokemónmi</a></li>
    <li><a href="{% url 'pokemoni:jedalen' %}">Jedáleň</a></li>
</ul>
<h1>Stránky družiniek</h1>
<ul>
    {% for druzinka in druzinky %}
    {% if druzinka.url_number %}
    <li><a href="{% url 'pokemoni:druzinka' druzinka.url_number %}">{{ druzinka.nazov }}</a></li>
    {% endif %}
    {% endfor %}
</ul>
{% else %}
<h1 id="no">Na túto stránku nemáte dostatočné oprávnenia!</h1>
<div id="debug">Pokračujte prihlásením do svojho účtu na <em>host_server_ip</em>/admin/login/?next=/admin/</div>
{% endif %}
</body>
</html>